<?php

namespace AppBundle\Repository;

/**
 * TagCollectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagCollectionRepository extends \Doctrine\ORM\EntityRepository
{
}
