<?php

namespace AppBundle\Repository;

/**
 * TagTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
