sonata_page:
    templates:
        news_details:
            path: 'AppBundle:pages:news_details.html.twig'
            name: 'News details page'
            containers:
                header:
                    name: Header
                content_top:
                    name: Top content
                content:
                    name: Main content
                content_bottom:
                    name: Bottom content
                footer:
                    name: Footer
            matrix:
                layout: |
                    HHHHHHHH
                    HHHHHHHH
                    TTTTTTTT
                    TTTTTTTT
                    CCCCCCCC
                    CCCCCCCC
                    BBBBBBBB
                    BBBBBBBB
                    FFFFFFFF
                mapping:
                    H: header
                    T: content_top
                    C: content
                    B: content_bottom
                    F: footer