imports:
    - { resource: blocks.yml }

services:
    app.menu_builder:
        class: AppBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory", "@doctrine.orm.entity_manager", "@sonata.page.cms.page"]
        tags:
            - { name: knp_menu.menu_builder, method: createHomepageChildrenMenu, alias: homepageChildren }
