services:
    app.sonata.block.rss:
        class: AppBundle\Blocks\RSSReaderBlock
        arguments:
            - app.sonata.block.rss
            - "@templating"
        tags:
            - { name: sonata.block }