services:
    app.sonata.block.rss:
        class: AppBundle\Blocks\RSSReaderBlock
        arguments:
            - app.sonata.block.rss
            - "@templating"
        tags:
            - { name: sonata.block }

    app.sonata.block.menu:
        class: AppBundle\Blocks\MenuBlock
        arguments:
            - app.sonata.block.menu
            - "@templating"
            - "@knp_menu.menu_provider"
        tags:
            - { name: sonata.block }

    app.menu_builder:
        class: AppBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }
            - { name: knp_menu.menu_builder, method: createSidebarMenu, alias: sidebar }
