imports:
    - { resource: blocks.yml }
    - { resource: admin.yml }

services:
    session.handler.pdo:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        public: false
        arguments:
            - "mysql:host=%database_host%;dbname=%database_name%"
            - { db_username: "%database_user%", db_password: "%database_password%" }
    app.menu_builder:
        class: AppBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory", "@doctrine.orm.entity_manager", "@request_stack"]
        tags:
            - { name: knp_menu.menu_builder, method: createHomepageChildrenMenu, alias: homepageChildren }
    app.locale_listener:
        class: AppBundle\EventListeners\LocaleListener
        arguments: ["@session", "%locale%"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
